## My Introduction to Scikit-Learn(sklearn)_Adisa Mumeen Suleiman
Here, I start working with the demonstration of the most useful functions of the vast Scikit-Learn library for Machine Learning.

#The flow is:

0. End-to-end sci-kit-learn workflow
1. Prepare and get data ready
2. Choose the right model/algorithm/estimator for our problems
3. Fit the prepared data to the model/algorithm
4. Use it to make predictions about the data after fitting
5. Evaluate the model for accuracy and performance
6. Improve the model by further experimentation and testing
7. Save and load my trained model
8. Put it all together in a single jupyter cell!!!!!!

# 0 . End-to-end sci-kit-learn workflow

In [1]:
# Get the prepared data ready. (heart disease data in our case)
import pandas as pd
import numpy as np
heart_disease = pd.read_csv("heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [2]:
# I want to use the other columns to predict what the target value will be as the output
# so values from the all the other columns will serve as my input parameter called x and y will be the
# target value from target column after our operation on the model which is the function or f(x)
#hence; x is he feature matrix and y is the label

x = heart_disease.drop("target", axis=1) #this drops the target column since we dont want it here
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [3]:
y = heart_disease["target"]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [4]:
# chose the right model and hyperparameters; hyperparameters are parameters that can be 
#changed to improve or affect the model
# we are using RandomForestClassifier model in our case
from sklearn.ensemble import RandomForestClassifier
#define the modelwith model or clf as name
model = RandomForestClassifier()

#choose hyperparameters I want for my model
# I used the default hyperparameter for this project
model.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [5]:
# I fit the model to the dataset by splitting the feature matrix , x and label, y into test and train data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.5)
#this split the x and y data classifications into train and test and pass them into the model/function with
#50% test size which means 50$ of the data is for training

#now lets fit
model.fit(x_train, y_train)
#wow! my model has been fitted to the data

RandomForestClassifier()

In [6]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
272,67,1,0,120,237,0,1,71,0,1.0,1,0,2
231,57,1,0,165,289,1,0,124,0,1.0,1,3,3
291,58,1,0,114,318,0,2,140,0,4.4,0,3,1
50,51,0,2,130,256,0,0,149,0,0.5,2,0,2
63,41,1,1,135,203,0,1,132,0,0.0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,41,0,1,126,306,0,1,163,0,0.0,2,0,2
229,64,1,2,125,309,0,1,131,1,1.8,1,0,3
107,45,0,0,138,236,0,0,152,1,0.2,1,0,2
141,43,1,0,115,303,0,1,181,0,1.2,1,0,2
38,65,0,2,155,269,0,1,148,0,0.8,2,0,2

In [7]:
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
289,55,0,0,128,205,0,2,130,1,2.0,1,1,3
198,62,1,0,120,267,0,1,99,1,1.8,1,2,3
181,65,0,0,150,225,0,0,114,0,1.0,1,3,3
293,67,1,2,152,212,0,0,150,0,0.8,1,0,3
98,43,1,2,130,315,0,1,162,0,1.9,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,67,1,0,100,299,0,0,125,1,0.9,1,2,2
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
233,64,1,0,120,246,0,0,96,1,2.2,0,1,2
68,44,1,1,120,220,0,1,170,0,0.0,2,0,2

In [8]:
y_train

272    0
231    0
291    0
50     1
63     1
      ..
134    1
229    0
107    1
141    1
38     1
Name: target, Length: 151, dtype: int64

In [9]:
y_test

289    0
198    0
181    0
293    0
98     1
      ..
253    0
8      1
2      1
233    0
68     1
Name: target, Length: 152, dtype: int64

In [10]:
# I want to make a prediction with my fitted model
y_preds = model.predict(x_test)
y_preds

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1],
      dtype=int64)

In [11]:
y_preds_1 = model.predict(x_train)
y_preds_1

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1],
      dtype=int64)

In [12]:
# I want to evaluate the module on training and test data, like checking how accuarate the model performs
model.score(x_train, y_train)
# 1.0 is the result, that is, it is 100% accurate

1.0

In [13]:
# But evaluating the test data, should not expect an 100% because the model wasnt trained with it
#lets see
model.score(x_test, y_test)
#huge!! fanstastic, though not 100 but very high 87%

0.8157894736842105

In [14]:
#mind you, asides accuracy test using the model.score() method, there are other ways of evaluation
#classification_report, confusion_matrix, accuracy score
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.84      0.72      0.78        68
           1       0.80      0.89      0.84        84

    accuracy                           0.82       152
   macro avg       0.82      0.81      0.81       152
weighted avg       0.82      0.82      0.81       152

In [15]:
confusion_matrix(y_test, y_preds )

array([[49, 19],
       [ 9, 75]], dtype=int64)

In [16]:
accuracy_score(y_test, y_preds)

0.8157894736842105

In [17]:
#I want to improve my model
# for example trying different amount of n_extimators instead of the default 100
#lets seed the array to fix set
np.random.seed(30)
for i in range(5, 100, 5): #group estimators in 5s up to 100
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
    print(f"Model accuracy on test is : {model.score(x_test, y_test) * 100:.2f}% accurate")
    print("")

Trying model with 5 estimators...
Model accuracy on test is : 72.37% accurate

Trying model with 10 estimators...
Model accuracy on test is : 76.97% accurate

Trying model with 15 estimators...
Model accuracy on test is : 80.92% accurate

Trying model with 20 estimators...
Model accuracy on test is : 81.58% accurate

Trying model with 25 estimators...
Model accuracy on test is : 81.58% accurate

Trying model with 30 estimators...
Model accuracy on test is : 77.63% accurate

Trying model with 35 estimators...
Model accuracy on test is : 80.92% accurate

Trying model with 40 estimators...
Model accuracy on test is : 79.61% accurate

Trying model with 45 estimators...
Model accuracy on test is : 78.29% accurate

Trying model with 50 estimators...
Model accuracy on test is : 80.92% accurate

Trying model with 55 estimators...
Model accuracy on test is : 81.58% accurate

Trying model with 60 estimators...
Model accuracy on test is : 80.26% accurate

Trying model with 65 estimators...
Model accuracy on test is : 80.92% accurate

Trying model with 70 estimators...
Model accuracy on test is : 80.92% accurate

Trying model with 75 estimators...
Model accuracy on test is : 78.95% accurate

Trying model with 80 estimators...
Model accuracy on test is : 82.24% accurate

Trying model with 85 estimators...
Model accuracy on test is : 78.29% accurate

Trying model with 90 estimators...
Model accuracy on test is : 79.61% accurate

Trying model with 95 estimators...
Model accuracy on test is : 82.24% accurate

In [18]:
#I want to save my module and reload it, using pickle
import pickle
pickle.dump(model, open("My-first random-forest-model.pkl", "wb")) #saves

In [19]:
# to reload it back
load_model = pickle.load(open("My-first random-forest-model.pkl", "rb"))
load_model

RandomForestClassifier(n_estimators=95)

## Converting string data to integer for Machine Learning

In [20]:
# let import the car-sales-extended data
import pandas as pd
car_sales = pd.read_csv("car-sales-extended.csv")
car_sales

       Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [21]:
# i split the data to feature matrix, (x_1) and label,(y)
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [22]:
X

       Make Colour  Odometer (KM)  Doors
0     Honda  White          35431      4
1       BMW   Blue         192714      5
2     Honda  White          84714      4
3    Toyota  White         154365      4
4    Nissan   Blue         181577      3
..      ...    ...            ...    ...
995  Toyota  Black          35820      4
996  Nissan  White         155144      3
997  Nissan   Blue          66604      4
998   Honda  White         215883      4
999  Toyota   Blue         248360      4

[1000 rows x 4 columns]

In [23]:
y

0      15323
1      19943
2      28343
3      13434
4      14043
       ...
995    32042
996     5716
997    31570
998     4001
999    12732
Name: Price, Length: 1000, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
# i split into train and test data, 80% for train and 20% for test
X_train, y_train, X_test, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2)

In [26]:
# i import the model module i want to use for machine learning this time RandomForestRegressor
# and not RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)

ValueError: could not convert string to float: 'Honda'

this error is because, the make, colour and doors column are in strings, the modelling machine does not understand string data, but integer(binary 
number)

I fix this by converting strings to binary numbers thus

In [27]:
# so we have to convert the strings to numbers, (binary) with sklearn 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categories = ["Make", "Colour", "Doors"] #defineing the columns we wan to convert
one_hot = OneHotEncoder() #invoking the onehotencoder function
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                 categories)],
                               remainder = "passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [28]:
# i put the transformed_x1 into dataframe, to make it more meaningful
pd.DataFrame(transformed_X)

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [29]:
# converting string to binary numbers can also be done by a pandas function called dummies

dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies # it could return 0 and 1 data or false and true

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,False,True,False,False,False,False,False,False,True
1,5,True,False,False,False,False,True,False,False,False
2,4,False,True,False,False,False,False,False,False,True
3,4,False,False,False,True,False,False,False,False,True
4,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,4,False,False,False,True,True,False,False,False,False
996,3,False,False,True,False,False,False,False,False,True
997,4,False,False,True,False,False,True,False,False,False
998,4,False,True,False,False,False,False,False,False,True
999,4,False,False,False,True,False,True,False,False,False

In [30]:
y1 = pd.DataFrame(y_test)

In [31]:
X1 = pd.DataFrame(X_test)
X1

     Price
800   8690
681   9492
292  14089
469  14931
839  10349
..     ...
83    5708
96   11392
234  13208
790   8253
999  12732

[800 rows x 1 columns]

In [32]:
pd.DataFrame(transformed_X)

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [95]:
# i refit this to check score again, since strings are now converted to integer(binary numbers)
from sklearn.model_selection import train_test_split
import numpy as np
np.random.seed(20)
X_train, y_train, x1, y1 = train_test_split(transformed_X, y, test_size=0.5)
model.fit(X_train, y_train)

RandomForestRegressor()

In [34]:
X_test

800     8690
681     9492
292    14089
469    14931
839    10349
       ...
83      5708
96     11392
234    13208
790     8253
999    12732
Name: Price, Length: 800, dtype: int64

In [36]:
X

       Make Colour  Odometer (KM)  Doors
0     Honda  White          35431      4
1       BMW   Blue         192714      5
2     Honda  White          84714      4
3    Toyota  White         154365      4
4    Nissan   Blue         181577      3
..      ...    ...            ...    ...
995  Toyota  Black          35820      4
996  Nissan  White         155144      3
997  Nissan   Blue          66604      4
998   Honda  White         215883      4
999  Toyota   Blue         248360      4

[1000 rows x 4 columns]

In [75]:
X_test

409     8980.0
285    17317.0
651    10061.0
138    14795.0
51     13698.0
        ...
932    24178.0
716     6917.0
72      5648.0
488    17076.0
756    17795.0
Name: Price, Length: 500, dtype: float64

In [77]:
X_test = pd.DataFrame(X_test)
X_test

       Price
409   8980.0
285  17317.0
651  10061.0
138  14795.0
51   13698.0
..       ...
932  24178.0
716   6917.0
72    5648.0
488  17076.0
756  17795.0

[500 rows x 1 columns]

In [86]:
y_test

457    10101.000
270     9379.000
612    16774.000
246     5273.000
766    17258.000
         ...
542    17520.000
537    20511.000
337    16045.665
606    31206.000
366     8704.000
Name: Price, Length: 500, dtype: float64

In [90]:
model.score(X_test, y_test)

c:\users\user\Desktop\ZTM_Projects\env\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(

ValueError: X has 1 features, but RandomForestRegressor is expecting 11 features as input.

# What if there are missing data
I will fix this in two ways:
1. filling in the missing data (inputation)
2. removing all the missing data alltogether, that it the entire row

In [43]:
# import the car-sales-missing data
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [44]:
# iget the total number of missing data for each attribute
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [65]:
# I want to convert the string colums to integer as before
X = car_sales_missing.drop("Price", axis=1) #split
y = car_sales_missing["Price"]
X

        Make Colour  Odometer (KM)  Doors
0    missing  White        35431.0    4.0
1    missing   Blue       192714.0    5.0
2    missing  White        84714.0    4.0
3    missing  White       154365.0    4.0
4    missing   Blue       181577.0    3.0
..       ...    ...            ...    ...
995  missing  Black        35820.0    4.0
996  missing  White       155144.0    3.0
997  missing   Blue        66604.0    4.0
998  missing  White       215883.0    4.0
999  missing   Blue       248360.0    4.0

[1000 rows x 4 columns]

In [66]:
y

0      15323.0
1      19943.0
2      28343.0
3      13434.0
4      14043.0
        ...
995    32042.0
996     5716.0
997    31570.0
998     4001.0
999    12732.0
Name: Price, Length: 1000, dtype: float64

In [65]:
# I want to convert the string colums to integer as before
X = car_sales_missing.drop("Price", axis=1) #split
y = car_sales_missing["Price"]
X

        Make Colour  Odometer (KM)  Doors
0    missing  White        35431.0    4.0
1    missing   Blue       192714.0    5.0
2    missing  White        84714.0    4.0
3    missing  White       154365.0    4.0
4    missing   Blue       181577.0    3.0
..       ...    ...            ...    ...
995  missing  Black        35820.0    4.0
996  missing  White       155144.0    3.0
997  missing   Blue        66604.0    4.0
998  missing  White       215883.0    4.0
999  missing   Blue       248360.0    4.0

[1000 rows x 4 columns]

In [50]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [69]:
# i have to fill the missing data or remove the missing rows. else there will be problem with scikitlearn
# i fill the make and colour with "missing". i fill the doors and price with its mean
# option 1: fill missing data with pandas
car_sales_missing["Make"] = car_sales_missing["Make"].fillna("missing")
car_sales_missing["Colour"] = car_sales_missing["Colour"].fillna("missing")
car_sales_missing["Doors"] = car_sales_missing["Doors"].fillna(4)
car_sales_missing["Odometer (KM)"] = car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean())
car_sales_missing["Price"] = car_sales_missing["Price"].fillna(car_sales["Price"].mean())

# note we can drop the missing data instead with car_sales_missing.dropna(inplace=True)

In [70]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

there no no more missing values, no NAN

In [67]:
# to convert
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one_hot = OneHotEncoder()
classification = ["Make", "Colour", "Doors"]
transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  classification)], 
                                remainder = "passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

array([[1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [1.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

#Fantastic, it has been converted to numerical data

Missing data can also be filled with scikit learn instead of pandas

# filling missing data with scikitlearn

In [98]:
# i have to reread the car_sales_missing data extended
car_sales_missing = pd.read_csv("car-sales-extended-missing-data.csv")
car_sales_missing

       Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [100]:
car_sales_missing.isna().sum() #alright the NAN rows are back, see below

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [106]:
#remove NaN from the price column
car_sales_missing.dropna(subset = ["Price"], inplace=True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [162]:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]
X.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
dtype: int64

In [163]:
y.isna().sum()

0

In [164]:
# now i fill in missing data cells with scikitlearn
# i import the SimpleInputer and ColumnTransformer modules
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

catg_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4) #4 is like the mean of the number of doors
num_imputer = SimpleImputer(strategy= "mean")

#define the features
catg_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

imputer = ColumnTransformer([("catg_imputer", catg_imputer, catg_features),
                              ("door_imputer", door_imputer, door_features),
                              ("num_imputer", num_imputer, num_features)])
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [165]:
#fantastic, it has worked
car_sales_filled = pd.DataFrame(filled_X, columns=["Make", "Colour", "Door", "Odometer (KM)"])
car_sales_filled

        Make Colour Door Odometer (KM)
0      Honda  White  4.0       35431.0
1        BMW   Blue  5.0      192714.0
2      Honda  White  4.0       84714.0
3     Toyota  White  4.0      154365.0
4     Nissan   Blue  3.0      181577.0
..       ...    ...  ...           ...
945   Toyota  Black  4.0       35820.0
946  missing  White  3.0      155144.0
947   Nissan   Blue  4.0       66604.0
948    Honda  White  4.0      215883.0
949   Toyota   Blue  4.0      248360.0

[950 rows x 4 columns]

In [166]:
car_sales_filled.isna().sum() # NO MORE MISSING VALUES

Make             0
Colour           0
Door             0
Odometer (KM)    0
dtype: int64

In [168]:
# its time to convert all strings to integer (binary numbers)
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
one_hot = OneHotEncoder()
cat_features = ["Make", "Colour", "Door"]
transformer = ColumnTransformer([("one_hot", 
                                  one_hot, cat_features)], 
                                remainder="passthrough")

transformed_X_filled = transformer.fit_transform(car_sales_filled)
transformed_X_filled

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [172]:
#beautiful, I got the car_sales_missing data filled and converted the strings to numbers
#its time to model it, so i will import my choice of model and splitter
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
model = RandomForestRegressor()
X_train, y_train, X_test, y_test = train_test_split(transformed_X_filled, y, test_size=0.2)
model.fit(X_train, y_train)

ValueError: sparse multilabel-indicator for y is not supported.